### ISSUE TITLE
footter view

### ISSUE THREAD

**Issue by MQTwist** [xiaopin/iOS-WaterfallLayout#4]
设置headerView的时候，必须得设置footterView，不然会崩溃。

**Comment by xiaopin** [comment]
如果只需要 header view 而不需要 footer view，那就不要实现 `- (CGFloat)collectionView:(UICollectionView *)collectionView layout:(XPCollectionViewWaterfallFlowLayout *)layout referenceHeightForFooterInSection:(NSInteger)section` 这个代理方法
